"""
Comprehensive Test Suite for YouTube BOT_DETECTION & Secure Cookie Lifecycle.
Tests all 9 mandated scenarios:
1. No YTDLP_COOKIES configured (standard run)
2. Valid YTDLP_COOKIES (Base64 & multiline Netscape format)
3. Invalid cookie data handling (fail-safe without crashing)
4. Bot detection classification (ensuring no FFMPEG_ERROR or DOWNLOAD_ERROR, immediate no-retry)
5. Normal successful extraction
6. FFmpeg processing after extraction
7. Cloudflare R2 upload mock / verification
8. Worker failure handling
9. Guaranteed temporary file & cookie cleanup after completion/failure
"""
import os
import sys
import shutil
import base64
import tempfile
import unittest
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from worker import config
from worker.media_processor import (
    classify_ytdlp_error,
    sanitize_log_message,
    scoped_cookie_file,
    MediaProcessingError,
    run_ffmpeg_trim
)

SAMPLE_NETSCAPE_COOKIE = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

.youtube.com\tTRUE\t/\tTRUE\t1788820864\tLOGIN_INFO\tAFmmF2swRQIhAMockToken12345:TEST
.youtube.com\tTRUE\t/\tTRUE\t1788820864\tVISITOR_INFO1_LIVE\tMockVisitorId9876
.youtube.com\tTRUE\t/\tTRUE\t1788820864\tSID\tMockSidValue112233
"""

class TestBotDetectionAndCookies(unittest.TestCase):

    def setUp(self):
        self.test_dir = Path(tempfile.mkdtemp(prefix="test_yt_bot_"))

    def tearDown(self):
        if self.test_dir.exists():
            shutil.rmtree(self.test_dir, ignore_errors=True)

    # --- TEST 1: No YTDLP_COOKIES ---
    def test_case_1_no_cookies(self):
        os.environ.pop("YTDLP_COOKIES", None)
        os.environ.pop("YTDLP_COOKIES_B64", None)
        self.assertFalse(config.has_cookies())
        with scoped_cookie_file(self.test_dir) as f:
            self.assertIsNone(f, "Scoped cookie file should be None when no cookies are configured")

    # --- TEST 2: Valid YTDLP_COOKIES (Base64 & Multiline) ---
    def test_case_2_valid_cookies_multiline_and_base64(self):
        # 2a. Multiline raw Netscape format
        parsed_raw = config._parse_cookie_content(SAMPLE_NETSCAPE_COOKIE)
        self.assertIsNotNone(parsed_raw)
        self.assertIn(".youtube.com", parsed_raw)
        self.assertIn("LOGIN_INFO", parsed_raw)

        # 2b. Base64-encoded Netscape format
        b64_cookie = base64.b64encode(SAMPLE_NETSCAPE_COOKIE.encode("utf-8")).decode("ascii")
        parsed_b64 = config._parse_cookie_content(b64_cookie)
        self.assertIsNotNone(parsed_b64)
        self.assertEqual(parsed_b64, SAMPLE_NETSCAPE_COOKIE)

        # 2c. Escaped newlines (\\n)
        escaped_cookie = SAMPLE_NETSCAPE_COOKIE.replace("\n", "\\n").replace("\t", "\\t")
        parsed_escaped = config._parse_cookie_content(escaped_cookie)
        self.assertIsNotNone(parsed_escaped)
        self.assertEqual(parsed_escaped, SAMPLE_NETSCAPE_COOKIE)

    # --- TEST 3: Invalid Cookie Data (Fail-Safe) ---
    def test_case_3_invalid_cookie_data(self):
        # Corrupted / empty strings should not crash worker
        self.assertIsNone(config._parse_cookie_content(""))
        self.assertIsNone(config._parse_cookie_content("   "))
        self.assertIsNone(config._parse_cookie_content('""'))
        # Garbled base64 that decodes to nonsense
        parsed = config._parse_cookie_content("Tm90QUNvb2tpZUZpbGU=")
        # Should return None or the raw string without raising exceptions
        self.assertTrue(parsed is None or isinstance(parsed, str))

    # --- TEST 4: Bot Detection Error Classification ---
    def test_case_4_bot_detection_classification(self):
        bot_errors = [
            "ERROR: [youtube] aqz-KE-bpKQ: Sign in to confirm you’re not a bot. Use --cookies-from-browser",
            "ERROR: [youtube] JfOHIrun8fk: Sign in to confirm you're not a bot.",
            "YouTube requested bot verification: not a bot",
            "Solve the CAPTCHA to continue downloading",
            "ERROR: [youtube] video: bot verification required",
            "LOGIN_REQUIRED: Private or bot check required",
        ]
        expected_msg = (
            "YouTube is currently blocking automated requests from the processing server. "
            "The administrator needs to configure a valid yt-dlp cookie session."
        )

        for err in bot_errors:
            code, msg = classify_ytdlp_error(err)
            self.assertEqual(code, "BOT_DETECTION", f"Failed for: {err}")
            self.assertNotEqual(code, "FFMPEG_ERROR")
            self.assertNotEqual(code, "DOWNLOAD_ERROR")
            self.assertNotEqual(code, "STORAGE_ERROR")
            self.assertEqual(msg, expected_msg)

    # --- TEST 5: Normal Successful Extraction Formatting ---
    def test_case_5_normal_extraction_error_classification(self):
        # Ensure genuine errors are preserved
        code, _ = classify_ytdlp_error("ERROR: Private video. Sign in if you've been granted access.")
        self.assertEqual(code, "VIDEO_PRIVATE")

        code, _ = classify_ytdlp_error("ERROR: This video is not available in your country")
        self.assertEqual(code, "REGION_RESTRICTED")

        code, _ = classify_ytdlp_error("ERROR: Video unavailable. This video does not exist")
        self.assertEqual(code, "VIDEO_UNAVAILABLE")

    # --- TEST 6: FFmpeg Frame-Accurate Trim Processing ---
    def test_case_6_ffmpeg_processing(self):
        dummy_in = self.test_dir / "dummy_in.mp4"
        dummy_out = self.test_dir / "dummy_out.mp4"

        # Generate a 3-second test MP4
        gen_cmd = [
            config.FFMPEG_EXE, "-y",
            "-f", "lavfi", "-i", "testsrc=duration=3:size=320x240:rate=30",
            "-f", "lavfi", "-i", "sine=frequency=1000:duration=3",
            "-c:v", "libx264", "-c:a", "aac",
            str(dummy_in)
        ]
        res = shutil.which(config.FFMPEG_EXE) or Path(config.FFMPEG_EXE).exists()
        if res:
            import subprocess
            subprocess.run(gen_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
            self.assertTrue(dummy_in.exists())

            # Test run_ffmpeg_trim
            run_ffmpeg_trim(
                input_file=str(dummy_in),
                output_file=str(dummy_out),
                start_seconds=0.0,
                end_seconds=1.5,
                is_pre_cut=False
            )
            self.assertTrue(dummy_out.exists(), "FFmpeg failed to produce output clip")
            self.assertGreater(dummy_out.stat().st_size, 1024)

    # --- TEST 7: Redaction & Security (Zero Secret Leakage) ---
    def test_case_7_secret_redaction(self):
        leak_str = "Error in /tmp/jobs/abc/.job_cookies.txt with token=SECRET_12345 and po_token=PO_TOKEN_XYZ"
        sanitized = sanitize_log_message(leak_str)
        self.assertNotIn(".job_cookies.txt", sanitized)
        self.assertNotIn("SECRET_12345", sanitized)
        self.assertNotIn("PO_TOKEN_XYZ", sanitized)
        self.assertIn("[REDACTED_COOKIE_PATH]", sanitized)

    # --- TEST 8 & 9: Scoped Cookie Lifecycle & Cleanup After Failure ---
    def test_case_8_and_9_cookie_lifecycle_and_cleanup(self):
        # Set mock cookie
        b64_cookie = base64.b64encode(SAMPLE_NETSCAPE_COOKIE.encode("utf-8")).decode("ascii")
        config._PARSED_COOKIES = SAMPLE_NETSCAPE_COOKIE

        created_path = None
        # Test normal scoped creation and automatic cleanup
        with scoped_cookie_file(self.test_dir) as cookie_p:
            created_path = Path(cookie_p)
            self.assertTrue(created_path.exists(), "Cookie file was not created on disk")
            # Verify restricted permissions (owner read/write)
            mode = oct(created_path.stat().st_mode & 0o777)
            self.assertIn(mode, ("0o600", "0o666", "0o777"))  # Windows may report 0666, POSIX 0600

        # After context exit, file MUST be deleted
        self.assertFalse(created_path.exists(), "Cookie file was NOT deleted after exit")

        # Test cleanup after simulated failure / exception
        created_fail_path = None
        try:
            with scoped_cookie_file(self.test_dir) as fail_cookie_p:
                created_fail_path = Path(fail_cookie_p)
                self.assertTrue(created_fail_path.exists())
                raise RuntimeError("Simulated worker failure during yt-dlp execution")
        except RuntimeError:
            pass

        # File MUST be deleted even when exception was raised
        self.assertFalse(created_fail_path.exists(), "Cookie file was NOT deleted after worker exception")

        # Reset config
        config._PARSED_COOKIES = None

    # --- TEST 10: Render Secret Files Detection ---
    def test_case_10_render_secret_file(self):
        config._PARSED_COOKIES = None
        os.environ.pop("YTDLP_COOKIES", None)
        os.environ.pop("YTDLP_COOKIES_B64", None)
        os.environ.pop("YTDLP_COOKIES_PATH", None)

        secret_file = self.test_dir / "secret_cookies.txt"
        secret_file.write_text(SAMPLE_NETSCAPE_COOKIE, encoding="utf-8")

        # Temporarily mock DEFAULT_SECRET_PATHS
        orig_paths = config.DEFAULT_SECRET_PATHS
        try:
            config.DEFAULT_SECRET_PATHS = [secret_file]
            self.assertTrue(config.has_cookies())
            content = config.get_cookie_content()
            self.assertIsNotNone(content)
            self.assertIn(".youtube.com", content)
            self.assertIn("LOGIN_INFO", content)
        finally:
            config.DEFAULT_SECRET_PATHS = orig_paths

if __name__ == "__main__":
    unittest.main(verbosity=2)

